// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6-BD_E8K6adYFOJ_6V9i5f7i8MKchmM0',
    appId: '1:283440465197:web:36a458298aa0257de0ffa4',
    messagingSenderId: '283440465197',
    projectId: 'chit-chat-app-98ef6',
    authDomain: 'chit-chat-app-98ef6.firebaseapp.com',
    storageBucket: 'chit-chat-app-98ef6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbOg_IhBuz91mufKCsIQh_E172kTNYYL4',
    appId: '1:283440465197:android:e83be5dd61fef032e0ffa4',
    messagingSenderId: '283440465197',
    projectId: 'chit-chat-app-98ef6',
    storageBucket: 'chit-chat-app-98ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0iFB-1MhhaK2hdr-3F3vS1rGODKHG57k',
    appId: '1:283440465197:ios:2f508e4fab08b601e0ffa4',
    messagingSenderId: '283440465197',
    projectId: 'chit-chat-app-98ef6',
    storageBucket: 'chit-chat-app-98ef6.appspot.com',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0iFB-1MhhaK2hdr-3F3vS1rGODKHG57k',
    appId: '1:283440465197:ios:af72d16dad06c63fe0ffa4',
    messagingSenderId: '283440465197',
    projectId: 'chit-chat-app-98ef6',
    storageBucket: 'chit-chat-app-98ef6.appspot.com',
    iosBundleId: 'com.example.chitChat.RunnerTests',
  );
}
